// Estrutura da aplicação (Afeta todas as páginas)


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >


        <header className="w-full flex justify-between items-center p-6 border-b bg-white shadow-sm">
          <div className="flex items-center gap-8">
            <Link href="/" className="text-2xl font-bold text-green-900">Silo Manager</Link>
            <nav className="space-x-6">
              <Link href="/silo" className="font-semibold text-gray-700 hover:text-green-900">Silos</Link>
              <Link href="/sensor" className="font-semibold text-gray-700 hover:text-green-900">Sensores</Link>
              <Link href="/device" className="font-semibold text-gray-700 hover:text-green-900">Dispositivos</Link>
              <Link href="/property" className="font-semibold text-gray-700 hover:text-green-900">Propriedades</Link>
              <Link href="/person" className="font-semibold text-gray-700 hover:text-green-900">Pessoas</Link>
              <Link href="/user" className="font-semibold text-gray-700 hover:text-green-900">Usuários</Link>
            </nav>
          </div>
          <div className="flex gap-4">
            <Link href="/login" className="bg-green-900 text-white px-4 py-2 rounded-full font-semibold hover:bg-green-800">Login</Link>
            <Link href="/register" className="border border-green-900 text-green-900 px-4 py-2 rounded-full font-semibold hover:bg-green-50">Registro</Link>
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
